export const POST_NEW_PASSWORD = "POST_NEW_PASSWORD";
export const POST_NEW_PASSWORD_SUCCESSFUL = "POST_NEW_PASSWORD_SUCCESSFUL";
export const POST_NEW_PASSWORD_ERROR = "POST_NEW_PASSWORD_ERROR";

export const CLEAR_MESSAGES = "CLEAR_MESSAGES"

export const REVIEW_USER = "REVIEW_USER";
export const REVIEW_USER_SUCCESS = "REVIEW_USER_SUCCESS";
export const REVIEW_USER_ERROR = "REVIEW_USER_ERROR";