export const GET_PAYMENT_GATEWAYS = "GET_PAYMENT_GATEWAYS";
export const GET_PAYMENT_GATEWAYS_SUCCESS = "GET_PAYMENT_GATEWAYS_SUCCESS";
export const GET_PAYMENT_GATEWAYS_ERROR = "GET_PAYMENT_GATEWAYS_ERROR";

export const VERIFY_TRANSACTION = "VERIFY_TRANSACTION";
export const VERIFY_TRANSACTION_SUCCESS = "VERIFY_TRANSACTION_SUCCESS";
export const VERIFY_TRANSACTION_ERROR = "VERIFY_TRANSACTION_ERROR";