export const GET_PAYMENT_GATEWAYS = "GET_PAYMENT_GATEWAYS";
export const GET_PAYMENT_GATEWAYS_SUCCESS = "GET_PAYMENT_GATEWAYS_SUCCESS";
export const GET_PAYMENT_GATEWAYS_ERROR = "GET_PAYMENT_GATEWAYS_ERROR";