export const FETCH_COUNTRY = "FETCH_COUNTRY";
export const FETCH_COUNTRY_SUCCESS = "FETCH_COUNTRY_SUCCESS";
export const FETCH_COUNTRY_ERROR = "FETCH_COUNTRY_ERROR";

export const FETCH_STATE = "FETCH_STATE";
export const FETCH_STATE_SUCCESS = "FETCH_STATE_SUCCESS";
export const FETCH_STATE_ERROR = "FETCH_STATE_ERROR";

export const FETCH_LGA = "FETCH_LGA";
export const FETCH_LGA_SUCCESS = "FETCH_LGA_SUCCESS";
export const FETCH_LGA_ERROR = "FETCH_LGA_ERROR";