export const FETCH_INSPECTIONS = 'FETCH_INSPECTIONS';
export const FETCH_INSPECTIONS_SUCCESSFUL = 'FETCH_INSPECTIONS_SUCCESSFUL';
export const FETCH_INSPECTIONS_ERROR = 'FETCH_INSPECTIONS_ERROR';

export const FETCH_EACH_INSPECTION = 'FETCH_EACH_INSPECTION';
export const FETCH_EACH_INSPECTION_SUCCESSFUL = 'FETCH_EACH_INSPECTION_SUCCESSFUL';
export const FETCH_EACH_INSPECTION_ERROR = 'FETCH_EACH_INSPECTION_ERROR';

export const POST_INSPECTION = 'POST_INSPECTION';
export const POST_INSPECTION_SUCCESSFUL = 'POST_INSPECTION_SUCCESSFUL';
export const POST_INSPECTION_FAILURE = 'POST_INSPECTION_FAILURE'