export const GET_LEASE_TERMINATIONS = "GET_LEASE_TERMINATIONS";
export const GET_LEASE_TERMINATIONS_SUCCESS = "GET_LEASE_TERMINATIONS_SUCCESS";
export const GET_LEASE_TERMINATIONS_ERROR = "GET_LEASE_TERMINATIONS_ERROR";

export const REVIEW_LEASE_TERMINATION = "REVIEW_LEASE_TERMINATION"; 
export const REVIEW_LEASE_TERMINATION_SUCCESS = "REVIEW_LEASE_TERMINATION_SUCCESS"; 
export const REVIEW_LEASE_TERMINATION_ERROR = "REVIEW_LEASE_TERMINATION_ERROR"; 

export const REQUEST_LEASE_TERMINATION = "REQUEST_LEASE_TERMINATION";
export const REQUEST_LEASE_TERMINATION_SUCCESS = "REQUEST_LEASE_TERMINATION_SUCCESS";
export const REQUEST_LEASE_TERMINATION_ERROR = "REQUEST_LEASE_TERMINATION_ERROR";

export const CLEAR_MESSAGES = "CLEAR_MESSAGES";