export const GET_BUY_APPLICATIONS = "GET_BUY_APPLICATIONS";
export const GET_BUY_APPLICATIONS_SUCCESS = "GET_BUY_APPLICATIONS_SUCCESS";
export const GET_BUY_APPLICATIONS_ERROR = "GET_BUY_APPLICATIONS_ERROR";

export const GET_EACH_BUY_APPLICATION = "GET_EACH_BUY_APPLICATION";
export const GET_EACH_BUY_APPLICATION_SUCCESS = "GET_EACH_BUY_APPLICATION_SUCCESS";
export const GET_EACH_BUY_APPLICATION_ERROR = "GET_EACH_BUY_APPLICATION_ERROR";

export const REVIEW_APPLICATION = "REVIEW_APPLICATION";
export const REVIEW_APPLICATION_SUCCESS = "REVIEW_APPLICATION_SUCCESS";
export const REVIEW_APPLICATION_ERROR = "REVIEW_APPLICATION_ERROR";

export const REVIEW_OFFER = "REVIEW_OFFER";
export const REVIEW_OFFER_SUCCESS = "REVIEW_OFFER_SUCCESS";
export const REVIEW_OFFER_ERROR = "REVIEW_OFFER_ERROR";

export const REVIEW_GUARANTOR = "REVIEW_GUARANTOR";
export const REVIEW_GUARANTOR_SUCCESS = "REVIEW_GUARANTOR_SUCCESS";
export const REVIEW_GUARANTOR_ERROR = "REVIEW_GUARANTOR_ERROR";

export const CLEAR_MESSAGES = "CLEAR_MESSAGES";