
export const FETCH_RENTAL = 'FETCH_RENTAL';
export const FETCH_RENTAL_SUCCESSFUL = 'FETCH_RENTAL_SUCCESSFUL';
export const FETCH_RENTAL_ERROR = 'FETCH_RENTAL_ERROR';

export const FETCH_RENTAL2 = 'FETCH_RENTAL2';
export const FETCH_RENTAL_SUCCESSFUL2 = 'FETCH_RENTAL_SUCCESSFUL2';
export const FETCH_RENTAL_ERROR2 = 'FETCH_RENTAL_ERROR2';


export const FETCH_RENTAL3 = 'FETCH_RENTAL3';
export const FETCH_RENTAL_SUCCESSFUL3 = 'FETCH_RENTAL_SUCCESSFUL3';
export const FETCH_RENTAL_ERROR3 = 'FETCH_RENTAL_ERROR3';

export const FETCH_RENTAL_RECOMMENDATION = 'FETCH_RENTAL_RECOMMENDATION';
export const FETCH_RENTAL_RECOMMENDATION_SUCCESSFUL = 'FETCH_RENTAL_RECOMMENDATION_SUCCESSFUL';
export const FETCH_RENTAL_RECOMMENDATION_ERROR = 'FETCH_RENTAL_RECOMMENDATION_ERROR';


export const PUT_TENANT_RECOMMENDATION = 'PUT_TENANT_RECOMMENDATION';
export const PUT_TENANT_RECOMMENDATION_SUCCESSFUL = 'PUT_TENANT_RECOMMENDATION_SUCCESSFUL';
export const PUT_TENANT_RECOMMENDATION_ERROR = 'PUT_TENANT_RECOMMENDATION_ERROR';

export const PUT_DATA_RECOMMENDATION = 'PUT_DATA_RECOMMENDATION';
export const PUT_DATA_RECOMMENDATION_SUCCESSFUL = 'PUT_DATA_RECOMMENDATION_SUCCESSFUL';
export const PUT_DATA_RECOMMENDATION_ERROR = 'PUT_DATA_RECOMMENDATION_ERROR'


export const DILIGENCE_RECOMMENDATION = 'DILIGENCE_RECOMMENDATION';
export const DILIGENCE_RECOMMENDATION_SUCCESSFUL = 'DILIGENCE_RECOMMENDATION_SUCCESSFUL';
export const DILIGENCE_RECOMMENDATION_ERROR = 'DILIGENCE_RECOMMENDATION_ERROR'