
export const FETCH_PROPERTIES = 'FETCH_PROPERTIES';
export const FETCH_PROPERTIES_SUCCESSFUL = 'FETCH_PROPERTIES_SUCCESSFUL';
export const FETCH_PROPERTIES_ERROR = 'FETCH_PROPERTIES_ERROR';

export const FETCH_EACH_PROPERTIES = 'FETCH_EACH_PROPERTIES';
export const FETCH_EACH_PROPERTIES_SUCCESSFUL = 'FETCH_EACH_PROPERTIES_SUCCESSFUL';
export const FETCH_EACH_PROPERTIES_ERROR = 'FETCH_EACH_PROPERTIES_ERROR';


export const CREATE_PROPERTIES = 'CREATE_PROPERTIES';
export const CREATE_PROPERTIES_SUCCESSFUL = 'CREATE_PROPERTIES_SUCCESSFUL';
export const CREATE_PROPERTIES_ERROR = 'CREATE_PROPERTIES_ERROR';

export const GET_PROPERTY_TYPES = 'GET_PROPERTY_TYPES';
export const GET_PROPERTY_TYPES_SUCCESS = 'GET_PROPERTY_TYPES_SUCCESS';
export const GET_PROPERTY_TYPES_ERROR = 'GET_PROPERTY_TYPES_ERROR';

export const GET_PROPERTY_SUBCATEGORY = 'GET_PROPERTY_SUBCATEGORY';
export const GET_PROPERTY_SUBCATEGORY_SUCCESS = 'GET_PROPERTY_SUBCATEGORY_SUCCESS';
export const GET_PROPERTY_SUBCATEGORY_ERROR = 'GET_PROPERTY_SUBCATEGORY_ERROR';
