
export const FETCH_PROPERTIES = 'FETCH_PROPERTIES';
export const FETCH_PROPERTIES_SUCCESSFUL = 'FETCH_PROPERTIES_SUCCESSFUL';
export const FETCH_PROPERTIES_ERROR = 'FETCH_PROPERTIES_ERROR';

export const FETCH_EACH_PROPERTIES = 'FETCH_EACH_PROPERTIES';
export const FETCH_EACH_PROPERTIES_SUCCESSFUL = 'FETCH_EACH_PROPERTIES_SUCCESSFUL';
export const FETCH_EACH_PROPERTIES_ERROR = 'FETCH_EACH_PROPERTIES_ERROR';


export const CREATE_PROPERTIES = 'CREATE_PROPERTIES';
export const CREATE_PROPERTIES_SUCCESSFUL = 'CREATE_PROPERTIES_SUCCESSFUL';
export const CREATE_PROPERTIES_ERROR = 'CREATE_PROPERTIES_ERROR';