
export const FETCH_PROPERTIES = 'FETCH_PROPERTIES';
export const FETCH_PROPERTIES_SUCCESSFUL = 'FETCH_PROPERTIES_SUCCESSFUL';
export const FETCH_PROPERTIES_ERROR = 'FETCH_PROPERTIES_ERROR';

export const FETCH_EACH_PROPERTIES = 'FETCH_EACH_PROPERTIES';
export const FETCH_EACH_PROPERTIES_SUCCESSFUL = 'FETCH_EACH_PROPERTIES_SUCCESSFUL';
export const FETCH_EACH_PROPERTIES_ERROR = 'FETCH_EACH_PROPERTIES_ERROR';


export const CREATE_PROPERTIES = 'CREATE_PROPERTIES';
export const CREATE_PROPERTIES_SUCCESSFUL = 'CREATE_PROPERTIES_SUCCESSFUL';
export const CREATE_PROPERTIES_ERROR = 'CREATE_PROPERTIES_ERROR';

export const UPDATE_UNIT = 'UPDATE_UNIT';
export const UPDATE_UNIT_SUCCESSFUL = 'UPDATE_UNIT_SUCCESSFUL';
export const UPDATE_UNIT_ERROR = 'UPDATE_UNIT_ERROR';

export const GET_PROPERTY_TYPES = 'GET_PROPERTY_TYPES';
export const GET_PROPERTY_TYPES_SUCCESS = 'GET_PROPERTY_TYPES_SUCCESS';
export const GET_PROPERTY_TYPES_ERROR = 'GET_PROPERTY_TYPES_ERROR';

export const GET_PROPERTY_SUBCATEGORY = 'GET_PROPERTY_SUBCATEGORY';
export const GET_PROPERTY_SUBCATEGORY_SUCCESS = 'GET_PROPERTY_SUBCATEGORY_SUCCESS';
export const GET_PROPERTY_SUBCATEGORY_ERROR = 'GET_PROPERTY_SUBCATEGORY_ERROR';

export const DUPLICATE_UNIT_PROPERTY = "DUPLICATE_UNIT_PROPERTY"
export const DUPLICATE_UNIT_PROPERTY_SUCCESS = "DUPLICATE_UNIT_PROPERTY_SUCCESS" 
export const DUPLICATE_UNIT_PROPERTY_ERROR = "DUPLICATE_UNIT_PROPERTY_ERROR" 

export const PUT_UNIT_PROPERTY = 'PUT_UNIT_PROPERTY';

export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';

export const DELETE_PROPERTY = 'DELETE_PROPERTY';
export const DELETE_PROPERTY_SUCCESS = "DELETE_PROPERTY_SUCCESS";
export const DELETE_PROPERTY_ERROR = "DELETE_PROPERTY_ERROR";