export const FETCH_BANKS = "FETCH_BANKS";
export const FETCH_BANKS_SUCCESSFUL = "FETCH_BANKS_SUCCESSFUL";
export const FETCH_BANKS_ERROR = 'FETCH_BANKS_ERROR';

export const POST_ACCOUNT = "POST_ACCOUNT";
export const POST_ACCOUNT_SUCCESSFUL = "POST_ACCOUNT_SUCCESSFUL";
export const POST_ACCOUNT_ERROR = "POST_ACCOUNT_ERROR";

export const GET_ACCOUNTS = "GET_ACCOUNTS";
export const GET_ACCOUNTS_SUCCESSFUL = "GET_ACCOUNTS_SUCCESSFUL";
export const GET_ACCOUNTS_ERROR = "GET_ACCOUNTS_ERROR";

export const CLEAR_MESSAGES = "CLEAR_MESSAGES";

export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
export const GET_TRANSACTIONS_SUCCESSFUL = "GET_TRANSACTIONS_SUCCESSFUL";
export const GET_TRANSACTIONS_ERROR = "GET_TRANSACTIONS_ERROR";

export const POST_TRANSACTION = "POST_TRANSACTION";
export const POST_TRANSACTION_SUCCESSFUL = "POST_TRANSACTION_SUCCESSFUL";
export const POST_TRANSACTION_ERROR = "POST_TRANSACTION_ERROR";

export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const DELETE_ACCOUNT_SUCCESS = "DELETE_ACCOUNT_SUCCESS";
export const DELETE_ACCOUNT_ERROR = "DELETE_ACCOUNT_ERROR";