
export const FETCH_APPOINTMENT = 'FETCH_APPOINTMENT';
export const FETCH_APPOINTMENT_SUCCESSFUL = 'FETCH_APPOINTMENT_SUCCESSFUL';
export const FETCH_APPOINTMENT_ERROR = 'FETCH_APPOINTMENT_ERROR';

export const PUT_ACCEPT_APPOINTMENT = 'PUT_ACCEPT_APPOINTMENT';
export const PUT_ACCEPT_APPOINTMENT_SUCCESS = 'PUT_ACCEPT_APPOINTMENT_SUCCESS';
export const PUT_ACCEPT_APPOINTMENT_ERROR = 'PUT_ACCEPT_APPOINTMENT_ERROR';

export const PUT_REJECT_APPOINTMENT = 'PUT_REJECT_APPOINTMENT'; 
export const PUT_REJECT_APPOINTMENT_SUCCESS = 'PUT_REJECT_APPOINTMENT_SUCCESS'; 
export const PUT_REJECT_APPOINTMENT_ERROR = 'PUT_REJECT_APPOINTMENT_ERROR'; 

export const CLEAR_MESSAGES = "CLEAR_MESSAGES";