export const GET_ALL_SERVICE_REQ = "GET_ALL_SERVICE_REQ";
export const GET_ALL_SERVICE_REQ_SUCCESS = "GET_ALL_SERVICE_REQ_SUCCESS";
export const GET_ALL_SERVICE_REQ_FAILURE = "GET_ALL_SERVICE_REQ_FAILURE";

export const GET_SERVICE_TYPES = "GET_SERVICE_TYPES";
export const GET_SERVICE_TYPES_SUCCESS = "GET_SERVICE_TYPES_SUCCESS";
export const GET_SERVICE_TYPES_FAILURE = "GET_SERVICE_TYPES_FAILURE";

export const POST_MAINTENANCE_REQ = "POST_MAINTENANCE_REQ";
export const POST_MAINTENANCE_REQ_SUCCESS = "POST_MAINTENANCE_REQ_SUCCESS";
export const POST_MAINTENANCE_REQ_FAILURE = "POST_MAINTENANCE_REQ_FAILURE";

export const GET_MAINTENANCE_REQ = "GET_MAINTENANCE_REQ";
export const GET_MAINTENANCE_REQ_SUCCESS = "GET_MAINTENANCE_REQ_SUCCESS";
export const GET_MAINTENANCE_REQ_FAILURE = "GET_MAINTENANCE_REQ_FAILURE";

export const FETCH_SERVICE = "FETCH_SERVICE";
export const FETCH_SERVICE_SUCCESS = "FETCH_SERVICE_SUCCESS";
export const FETCH_SERVICE_FAILURE = "FETCH_SERVICE_FAILURE";

export const GET_INVOICE_DETS = "GET_INVOICE_DETS";
export const GET_INVOICE_DETS_SUCCESS = "GET_INVOICE_DETS_SUCCESS";
export const GET_INVOICE_DETS_ERROR = "GET_INVOICE_DETS_ERROR";

export const ACCEPT_INVOICE = "ACCEPT_INVOICE";
export const ACCEPT_INVOICE_SUCCESS = "ACCEPT_INVOICE_SUCCESS";
export const ACCEPT_INVOICE_ERROR = "ACCEPT_INVOICE_ERROR";

export const REJECT_INVOICE = "REJECT_INVOICE";
export const REJECT_INVOICE_SUCCESS = "REJECT_INVOICE_SUCCESS";
export const REJECT_INVOICE_ERROR = "REJECT_INVOICE_ERROR";

export const ACCEPT_SERVICE_AGREEMENT = "ACCEPT_SERVICE_AGREEMENT";
export const ACCEPT_SERVICE_AGREEMENT_SUCCESS = "ACCEPT_SERVICE_AGREEMENT_SUCCESS";
export const ACCEPT_SERVICE_AGREEMENT_ERROR = "ACCEPT_SERVICE_AGREEMENT_ERROR";

export const CLEAR_MESSAGES = "CLEAR_MESSAGES";

export const FETCH_MAINTENANCE = "FETCH_MAINTENANCE";
export const FETCH_MAINTENANCE_SUCCESS = "FETCH_MAINTENANCE_SUCCESS";
export const FETCH_MAINTENANCE_FAILURE = "FETCH_MAINTENANCE_FAILURE";

export const GET_SERVICE_PROVIDERS = "GET_SERVICE_PROVIDERS";
export const GET_SERVICE_PROVIDERS_SUCCESS = "GET_SERVICE_PROVIDERS_SUCCESS";
export const GET_SERVICE_PROVIDERS_ERROR = "GET_SERVICE_PROVIDERS_ERROR";

export const INIT_PART_PAYMENT = "INIT_PART_PAYMENT";
export const INIT_PART_PAYMENT_SUCCESS = "INIT_PART_PAYMENT_SUCCESS";
export const INIT_PART_PAYMENT_ERROR = "INIT_PART_PAYMENT_ERROR";

export const INIT_COMPLETE_PAYMENT = "INIT_COMPLETE_PAYMENT";
export const INIT_COMPLETE_PAYMENT_SUCCESS = "INIT_COMPLETE_PAYMENT_SUCCESS";
export const INIT_COMPLETE_PAYMENT_ERROR = "INIT_COMPLETE_PAYMENT_ERROR";