export const GET_ALL_SERVICE_REQ_COMPLETE = "GET_ALL_SERVICE_REQ";
export const GET_ALL_SERVICE_REQ_COMPLETE_SUCCESS = "GET_ALL_SERVICE_REQ_SUCCESS";
export const GET_ALL_SERVICE_REQ_COMPLETE_FAILURE = "GET_ALL_SERVICE_REQ_FAILURE";
export const GET_ALL_SERVICE_REQ_PENDING = "GET_ALL_SERVICE_REQ_PENDING";
export const GET_ALL_SERVICE_REQ_PENDING_SUCCESS = "GET_ALL_SERVICE_REQ_PENDING_SUCCESS";
export const GET_ALL_SERVICE_REQ_PENDING_FAILURE = "GET_ALL_SERVICE_REQ_PENDING_FAILURE";