export const GET_ALL_SERVICE_REQ = "GET_ALL_SERVICE_REQ";
export const GET_ALL_SERVICE_REQ_SUCCESS = "GET_ALL_SERVICE_REQ_SUCCESS";
export const GET_ALL_SERVICE_REQ_FAILURE = "GET_ALL_SERVICE_REQ_FAILURE";

export const GET_SERVICE_TYPES = "GET_SERVICE_TYPES";
export const GET_SERVICE_TYPES_SUCCESS = "GET_SERVICE_TYPES_SUCCESS";
export const GET_SERVICE_TYPES_FAILURE = "GET_SERVICE_TYPES_FAILURE";

export const POST_MAINTENANCE_REQ = "POST_MAINTENANCE_REQ";
export const POST_MAINTENANCE_REQ_SUCCESS = "POST_MAINTENANCE_REQ_SUCCESS";
export const POST_MAINTENANCE_REQ_FAILURE = "POST_MAINTENANCE_REQ_FAILURE";

export const GET_MAINTENANCE_REQ = "GET_MAINTENANCE_REQ";
export const GET_MAINTENANCE_REQ_SUCCESS = "GET_MAINTENANCE_REQ_SUCCESS";
export const GET_MAINTENANCE_REQ_FAILURE = "GET_MAINTENANCE_REQ_FAILURE";

export const FETCH_SERVICE = "FETCH_SERVICE";
export const FETCH_SERVICE_SUCCESS = "FETCH_SERVICE_SUCCESS";
export const FETCH_SERVICE_FAILURE = "FETCH_SERVICE_FAILURE";

export const CLEAR_MESSAGES = "CLEAR_MESSAGES";

export const FETCH_MAINTENANCE = "FETCH_MAINTENANCE";
export const FETCH_MAINTENANCE_SUCCESS = "FETCH_MAINTENANCE_SUCCESS";
export const FETCH_MAINTENANCE_FAILURE = "FETCH_MAINTENANCE_FAILURE";

export const GET_SERVICE_PROVIDERS = "GET_SERVICE_PROVIDERS";
export const GET_SERVICE_PROVIDERS_SUCCESS = "GET_SERVICE_PROVIDERS_SUCCESS";
export const GET_SERVICE_PROVIDERS_ERROR = "GET_SERVICE_PROVIDERS_ERROR";