export const FETCH_EXPIRING = 'FETCH_EXPIRING';
export const FETCH_EXPIRING_SUCCESSFUL = 'FETCH_EXPIRING_SUCCESSFUL';
export const FETCH_EXPIRING_ERROR = 'FETCH_EXPIRING_ERROR';


export const FETCH_EXPIRING_SIXTY = 'FETCH_EXPIRING_SIXTY ';
export const FETCH_EXPIRING_SUCCESSFUL_SIXTY  = 'FETCH_EXPIRING_SUCCESSFUL_SIXTY ';
export const FETCH_EXPIRING_ERROR_SIXTY  = 'FETCH_EXPIRING_ERROR_SIXTY';


export const FETCH_EXPIRING_ONETWENTY = 'FETCH_EXPIRING_ONETWENTY  ';
export const FETCH_EXPIRING_SUCCESSFUL_ONETWENTY  = 'FETCH_EXPIRING_SUCCESSFUL_ONETWENTY  ';
export const FETCH_EXPIRING_ERROR_ONETWENTY   = 'FETCH_EXPIRING_ERROR_ONETWENTY ';

export const FETCH_EXPIRING_ZERO = 'FETCH_EXPIRING_ZERO';
export const FETCH_EXPIRING_SUCCESSFUL_ZERO  = 'FETCH_EXPIRING_SUCCESSFUL_ZERO';
export const FETCH_EXPIRING_ERROR_ZERO   = 'FETCH_EXPIRING_ERROR_ZERO ';